// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixwnucfebopjqcokohhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4d251Y2ZlYm9wanFjb2tvaGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODMxMjQsImV4cCI6MjA3MTM1OTEyNH0.6XjMw9dOjDgc_pwYNa-J6bBdfKtyDT2I4UcQQlUvplE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});